# Generated by Django 6.0.4 on 2026-04-30 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('answers_text', models.TextField(verbose_name='Текст ответов')),
                ('ai_score', models.IntegerField(verbose_name='Оценка ИИ')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='Резюме ИИ')),
                ('ai_probability', models.FloatField(default=0.0, verbose_name='Вероятность')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кандидаты',
            },
        ),
    ]
